config/routes.rb
Rails.application.routes.draw do
  resources :gardens do
    resources :plants, only: :create
  end
  resources :plants, only: :destroy do
    resources :plant_tags, only: [:new,:create]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/garden.rb
class Garden < ApplicationRecord
  validates_presence_of :name,:banner_url
  has_many :plants, dependent: :destroy
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :garden
  has_many :plant_tags, dependent: :destroy
  has_many :tags, through: :plant_tags
end

app/models/plant_tag.rb
class PlantTag < ApplicationRecord
  belongs_to :tag
  belongs_to :plant
  validates :tag, uniqueness: {scope: :plant, message: "already added!"}
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :plant_tags, dependent: :destroy
  has_many :plants, through: :plant_tags
  validates :name, presence: true
  validates :name, length: {minimum:3, maximum:10}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  before_action :set_garden, only: %i[ show edit update destroy ]

  # GET /gardens or /gardens.json
  def index
    @gardens = Garden.all
  end

  # GET /gardens/1 or /gardens/1.json
  def show
    @plant = Plant.new
  end

  # GET /gardens/new
  def new
    @garden = Garden.new
  end

  # GET /gardens/1/edit
  def edit
  end

  # POST /gardens or /gardens.json
  def create
    @garden = Garden.new(garden_params)

    respond_to do |format|
      if @garden.save
        format.html { redirect_to garden_url(@garden), notice: "Garden was successfully created." }
        format.json { render :show, status: :created, location: @garden }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @garden.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gardens/1 or /gardens/1.json
  def update
    respond_to do |format|
      if @garden.update(garden_params)
        format.html { redirect_to garden_url(@garden), notice: "Garden was successfully updated." }
        format.json { render :show, status: :ok, location: @garden }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @garden.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gardens/1 or /gardens/1.json
  def destroy
    @garden.destroy

    respond_to do |format|
      format.html { redirect_to gardens_url, notice: "Garden was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_garden
      @garden = Garden.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def garden_params
      params.require(:garden).permit(:name, :banner_url)
    end
end

app/controllers/plant_tags_controller.rb
class PlantTagsController < ApplicationController
  def new
    @plant = Plant.find(params[:plant_id])
    @plant_tag = PlantTag.new
  end

  def create
      @plant = Plant.find(params[:plant_id])
      #im receiving multple tags
      @tags = Tag.where(id: params[:plant_tag][:tag_id])
      #iterate over them
      @tags.each do |tag|
        #create a plant tag for each of the tags
        plant_tag = PlantTag.new(plant: @plant, tag: tag)
        plant_tag.save
      end
      redirect_to garden_path(@plant.garden)
  end




end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  def create
    @garden = Garden.find(params[:garden_id])
    @plant = Plant.new(plant_params)
    @plant.garden = @garden
    if @plant.save
      redirect_to @garden
    else
      render "garden/show", status: :unprocessable_entity
    end
  end

  def destroy
    @plant = Plant.find(params[:id])
    @plant.destroy
    redirect_to garden_path(@plant.garden), status: :see_other
  end


  private
  def plant_params
    params.require(:plant).permit(:name,:image_url)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gardens_helper.rb
module GardensHelper
end

app/helpers/plant_tags_helper.rb
module PlantTagsHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/gardens/_form.html.erb
<%= simple_form_for(@garden) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :banner_url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/gardens/_garden.html.erb
<div id="<%= dom_id garden %>">
  <p>
    <strong>Name:</strong>
    <%= garden.name %>
  </p>

  <p>
    <strong>Banner url:</strong>
    <%= garden.banner_url %>
  </p>

</div>

app/views/gardens/edit.html.erb
<h1>Editing garden</h1>

<%= render "form", garden: @garden %>

<br>

<div>
  <%= link_to "Show this garden", @garden %> |
  <%= link_to "Back to gardens", gardens_path %>
</div>

app/views/gardens/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Gardens</h1>

<div id="gardens">
  <% @gardens.each do |garden| %>
    <%= render garden %>
    <p>
      <%= link_to "Show this garden", garden %>
    </p>
  <% end %>
</div>

<%= link_to "New garden", new_garden_path %>

app/views/gardens/new.html.erb
<h1>New garden</h1>

<%= render "form", garden: @garden %>

<br>

<div>
  <%= link_to "Back to gardens", gardens_path %>
</div>

app/views/gardens/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url( '<%= @garden.banner_url %>');">
  <div class="container">
    <h1><%= @garden.name %></h1>
  </div>
</div>
<div class="container my-3">
  <div class="row">
    <% @garden.plants.each do |plant| %>
      <div class="col-4">
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= plant.image_url %>')">
          <div class="card-tags">
            <% plant.tags.each do |tag| %>
              <span><%= tag.name %></span>
            <% end %>
            <%= link_to "+", new_plant_plant_tag_path(plant), class: "add-tag-button" %>
          </div>
        <%= plant.name %>
        <%= button_to "X", plant_path(plant), method: :delete, class: "btn-x" %>
        <%#= link_to "X", plant_path(plant), data: {turbo_method: :delete, turbo_confirm: "Are you Sure?"} %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-4">
      <h4>Add a plant:</h4>
      <%= simple_form_for [@garden,@plant] do |f| %>
      <%= f.input :name, placeholder: "Tree" %>
      <%= f.input :image_url, placeholder: "cool_image.jpg" %>
      <%= f.submit "ADD", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GardensAndPlants949</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css" integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plant_tags/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col">
      <h1>Add a new Tag for <%= @plant.name %></h1>
      <%= simple_form_for [@plant,@plant_tag] do |f| %>
        <%= f.association :tag, input_html: {multiple: true, data:{controller: "tom-select"}}, include_hidden: false %>
        <%= f.submit "Add a Tag", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>